CREATE TABLE `states` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stateCode` varchar(2) NOT NULL,
	`stateName` varchar(100) NOT NULL,
	`implementationStatus` enum('not_implemented','pending_approval','approved_not_active','active','suspended','terminated') NOT NULL DEFAULT 'not_implemented',
	`approvalDate` timestamp,
	`effectiveDate` timestamp,
	`nextDeadline` timestamp,
	`weeklyHoursRequired` int,
	`monthlyHoursRequired` int,
	`hoursDescription` text,
	`qualifyingActivities` json,
	`exemptions` json,
	`reportingFrequency` varchar(50),
	`reportingMethod` text,
	`reportingDeadline` text,
	`agencyName` varchar(255),
	`agencyPhone` varchar(50),
	`agencyEmail` varchar(255),
	`agencyWebsite` text,
	`summary` text,
	`additionalNotes` text,
	`primarySourceUrl` text,
	`lastVerifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `states_id` PRIMARY KEY(`id`),
	CONSTRAINT `states_stateCode_unique` UNIQUE(`stateCode`)
);
--> statement-breakpoint
CREATE TABLE `update_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runType` enum('weekly_automated','manual_all','manual_single') NOT NULL DEFAULT 'weekly_automated',
	`totalStates` int NOT NULL DEFAULT 51,
	`completedStates` int NOT NULL DEFAULT 0,
	`failedStates` int NOT NULL DEFAULT 0,
	`skippedStates` int NOT NULL DEFAULT 0,
	`status` enum('running','completed','failed','cancelled') NOT NULL DEFAULT 'running',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`triggeredBy` varchar(100),
	`summary` text,
	CONSTRAINT `update_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `updates_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stateId` int NOT NULL,
	`stateCode` varchar(2) NOT NULL,
	`updateType` enum('automated','manual','initial_seed') NOT NULL DEFAULT 'automated',
	`fieldChanged` varchar(100) NOT NULL,
	`previousValue` text,
	`newValue` text,
	`changeDescription` text,
	`sourceUrl` text,
	`sourceType` varchar(50),
	`status` enum('success','failed','pending','skipped') NOT NULL DEFAULT 'success',
	`errorMessage` text,
	`triggeredBy` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `updates_log_id` PRIMARY KEY(`id`)
);
